Code Review Process
masterdatascience-UIMP-UC/predictaas-api-server pull request #5
Opened 2022-02-23 18:18 UTC by luciaalap

2022-02-23 18:23 UTC, Yosoycoder approved these changes

2022-02-23 18:24 UTC, orviz requested changes

2022-02-23 18:24 UTC, orviz commented on CONTRIBUTING.md
> +**Code Review Process**
Sections start with '##'

2022-02-28 16:44 UTC, orviz approved these changes

2022-02-28 16:44 UTC, merged